---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: endpoint/repository:imagetag
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8082


